name: crypt4gh-rust
version: "0.1.0"
author: Roberto <roberto.ariosa@crg.eu>
about: Utility for the cryptographic GA4GH standard, reading from stdin and outputting to stdout.
args:
    - verbose:
        short: v
        long: verbose
        about: Sets the level of verbosity
subcommands:
    - encrypt:
        args:
            - sk:
                long: sk
                about: Curve25519-based Private key
                takes_value: true
                value_name: path
            - recipient_pk:
                required: true
                long: recipient_pk
                about: Recipient's Curve25519-based Public key
                takes_value: true
                value_name: path
            - range:
                required: false
                long: range
                about: Byte-range either as  <start-end> or just <start> (Start included, End excluded)
                takes_value: true
                value_name: start-end
    - decrypt:
        args:
            - sk:
                long: sk
                about: Curve25519-based Private key.
                takes_value: true
                value_name: path
            - sender_pk:
                required: false
                long: sender_pk
                about: Peer's Curve25519-based Public key to verify provenance (akin to signature)
                takes_value: true
                value_name: path

