[package]
name = "crypt4gh"
version = "0.1.1"
authors = ["Roberto <roberto.ariosa@crg.eu>"]
edition = "2018"
license = "Apache-2.0"
description = "Encryption and decryption implementation of the Crypt4GH encryption format."
repository = "https://github.com/EGA-archive/crypt4gh-rust"
documentation = "https://docs.rs/crypt4gh"
keywords = ["crypt4gh", "genetics", "genome", "encryption", "c4gh"]
categories = ["cryptography", "encoding"]
readme = "README.md"

[lib]
name = "crypt4gh"
path = "src/lib.rs"

[[bin]]
name = "crypt4gh"
path = "src/bin.rs"

[dependencies]
clap = { version = "3.0.0-beta.2", features = ["yaml"] }
regex = "1.4.2"
rpassword = "5.0.0"
sodiumoxide = "0.2.6"
base64 = "0.13.0"
lazy_static = "1.4.0"
rust-crypto = "0.2.36"
bincode = "1.3.1"
serde = { version = "1.0.117", features = ["derive"] }
log = "0.4.11"
pretty_env_logger = "0.4.0"
anyhow = "1.0.34"
libsodium-sys = "0.2.6"

[dev-dependencies]
rand = "0.7.3"

[profile.release]
lto = true
overflow-checks = true
